### ISSUE TITLE
Is `safelist` working in the current version?

### ISSUE THREAD

**Issue by Mexican-Man** [Jax-p/vite-plugin-html-purgecss#1]
Everything else seems to be working fine. I'm using Bootstrap v5.1.1 ([here's the file](https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.css)). These rules are getting stripped out:
```css
.carousel-item-next:not(.carousel-item-start),
.active.carousel-item-end {
  transform: translateX(100%);
}

.carousel-item-prev:not(.carousel-item-end),
.active.carousel-item-start {
  transform: translateX(-100%);
}
```
so I've tried adding this to my vite config
```js
 htmlPurge({
  safelist: [ 'carousel-item-next', 'carousel-item-next', 'carousel-item-prev' ]
}),
```
as well as
```js
 htmlPurge({
  safelist: [ '/carousel/' ]
}),
```
with no luck. I'm new with purgecss, so I apologize if I'm missing something.
